apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
spec:
  storageClassName: ping-pong-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
